name: secrets-actions

on: push
jobs: 
  top-secret:
    runs-on: ubuntu-latest
    env: 
      SECRET_KEY: ${{ secrets.SECRET }}

    steps: 
      - name: test one
        run: echo "My secret is ${{ secrets.SECRET }}"
